### ISSUE TITLE
No way to see the final result of a transform

### ISSUE THREAD

**Issue by Cadiboo** [MinecraftForge/CoreMods#11]
I think there should be a way to see the final result of a transformed class/method after all transformers have run. In 1.12.2 I did this by compiling the class and creating text files containing all the instructions both pre-transform and post-transform. I think that something similar should be implemented that provides a way to dump the bytecode of specific transformed classes before and after transformations (which classes would depend on launch arguments passed in) for debugging.

**Comment by ichttt** [comment]
There is already a possibility to dump all classes that have transformed by anything in modlauncher, see https://github.com/cpw/modlauncher/blob/745b6f9a12a682bce3afec2aeaa530ad93a7cde8/src/main/java/cpw/mods/modlauncher/ClassTransformer.java#L97

**Comment by Cadiboo** [comment]
Thanks!
