### ISSUE TITLE
No way to tell if the coremod is in a developer environment

### ISSUE THREAD

**Issue by Cadiboo** [MinecraftForge/CoreMods#12]
Related to #10 
I think that there needs to be a way to change the modifications based on if the coremod is in a deobf environment or not so that field/method names can be handled properly. If something like #10 is not done I think that a simple method that returns a boolean in the ASMAPI would be alright.

**Comment by cpw** [comment]
closed with 0651e556f5c5b1366e18a714165a2e67ccac4c12
