### ISSUE TITLE
ASMAPI.getSystemPropertyFlag using wrong Boolean conversion

### ISSUE THREAD

**Issue by jediminer543** [MinecraftForge/CoreMods#31]
As of writing; the ability for coremods to access properties is broken due to the method of boolean conversion.

It currently uses Boolean.getBoolean which reads the given string as a property name and the looks at what the value of that property is. To make a flag "flag" be true pass `-Dcoremod.flag=true -Dtrue=true'

Responsible line:
https://github.com/MinecraftForge/CoreMods/blob/38176588f88aeff00e2bdca2ea60a826212f1920/src/main/java/net/minecraftforge/coremod/api/ASMAPI.java#L55

**Comment by jediminer543** [comment]
Also as a request, as the current behaviour is that any flag that isn't "defined" (in the current wierd way) is to let it be false can this behaviour be preserved, instead of the presumably current aim of making it be true unless falsified

**Comment by PaintNinja** [comment]
Fixed by #41
