### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [MinecraftForge/CoreMods#36]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

**My disclosures always follow Github's 90-day [disclosure policy](https://securitylab.github.com/advisories#policy) (I'm not an employee of Github, I just like their policy).**

**Comment by dpeter99** [comment]
Hi there!
While we do not have a draft security advisory, we take the chance of a seccurity risk seriously. The best course of action to report this and try to mitigate it would be to contact us through discord. You can find our official [discord here](https://discord.gg/forge). You can find me there or message me directly throug my account discord account (dpeter99# 0001). 
Thank you for contacting us!

**Comment by intrigus-lgtm** [comment]
Closing because what I found is not a security boundary in this case.
