### ISSUE TITLE
ClassNode is not on the allowed class list

### ISSUE THREAD

**Issue by noeppi-noeppi** [MinecraftForge/CoreMods#38]
`ClassNode` is not on the allowed class list, so using `Java.type('org.objectweb.asm.tree.ClassNode')` crashes. However `ClassNode` is required to use the `CLASS` target.

**Comment by Jonathing** [comment]
I don't think it is necessary to expose the `ClassNode` class, since you can access all its members without needing to important. The only thing you'd get is the ability to create new class nodes. Why would you need to do this?
