### ISSUE TITLE
[Feature Request] Add way to export data from the JS sandbox

### ISSUE THREAD

**Issue by ByThePowerOfScience** [MinecraftForge/CoreMods#60]
In some cases, you need to export the data you get from the ASM phase.  Currently, the only way to do that is to use the logger, which is only helpful for debugging and isn't very helpful for that either.

Is there any chance an `outputFile` function could be added to the API?

**Comment by Jonathing** [comment]
It might be a bit difficult since the only filesystem each coremod has access to at the time of evaluation is the read-only filesystem of the jar. I'm sure it's possible though.

What would a use case for this be though? If you need complex data it'd make sense.

Although you could always do the scuffed solution of coremodding your own class and editing a static final boolean field 💀💀💀💀💀

**Comment by Jonathing** [comment]
Motherfucker I was joking 😭😭😭😭😭

Anyways if you need debugging data I honestly would just stick to the logger. Use some phrase you can easily CTRL + F for in the logs or console. I use ASMAPI.classNodeToString (or similar) all the time to check the resultant Bytecode.

**Comment by Jonathing** [comment]
Ah you know what: I remembered an idea I had of having CoreMods be able to dump modified classes after they've been transformed. The issue with that is CoreMods can't do that, I think ModLauncher has to. Although CoreMods *could* be able to dump the class after your specific coremod has been applied, but it wouldn't account for any coremods that would come after.

**Comment by LexManos** [comment]
I'm hesitant to allow file system access to the JS sandbox as that could cause a lot of weirdness.
What type of data are you wanting to export?
Why does it need to be on disc, and not in memory?
If its just for debugging things like Jonathing said, i'd stick to the logger/IDE. 

But on a related not yes, we need to finalize/make the classpath dumping a first class feature in SecureModules.

**Comment by Jonathing** [comment]
> But on a related not yes, we need to finalize/make the classpath dumping a first class feature in SecureModules.

100%, but yeah it can't be done in CoreMods.

**Comment by Jonathing** [comment]
I'm going to close this for now as it is out of scope for CoreMods. I'll open a related issue in MinecraftForge/SecureModules when the time comes for it, as I would like to have class dumping in a manner similar to how Mixin does it with `mixin.debug.export`.
