### ISSUE TITLE
Module requires JetBrains annotations at production

### ISSUE THREAD

**Issue by Jonathing** [MinecraftForge/CoreMods#65]
I haven't gotten the chance to test CoreMods in production, so this is unfortunately the first time I've run into this issue. It looks like the `module-info.java` we made for CoreMods requires JetBrains annotations to be present as well. This is despite the fact that Forge does not include JetBrains annotations in any version.

**Comment by LexManos** [comment]
Yes the annotations are compile time only, so it should be a requires static.
