### ISSUE TITLE
Nashorn exposes java, javax, javafx, com, edu, org packages for scripts by default

### ISSUE THREAD

**Issue by Exidex** [MinecraftForge/CoreMods#8]
https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/api.html
As per title you can write this in script
```javascript
print(java.lang.Thread.currentThread().getContextClassLoader());
```
or
```javascript
com.exidex.examplemod.ExampleMod.print();
```

It can be disabled via nashorn args
```java
ScriptEngine engine = new NashornScriptEngineFactory().getScriptEngine("--no-java", "-doe");
```
(-doe is enabled by default, prints stacktrace on error)

But as ASM uses some java classes like lists, those need to be whitelisted manually

**Comment by Exidex** [comment]
My bad, with --no-java, Java object is not available there will be no way to import classes with Java.type() so there needs to be another way

**Comment by cpw** [comment]
Are you sure about the Java access analysis. The doc you link explicitly calls out a java class and prevents it, using a classfilter, just as I have implemented..

In any case, I'll be testing this.

**Comment by Exidex** [comment]
I pasted wrong link apparently 
https://wiki.openjdk.java.net/display/Nashorn/Nashorn+extensions
Paragraph: Packages, java, javax, javafx, com, edu, org

**Comment by cpw** [comment]
I still don't see how this bypasses the ClassFilter?

**Comment by cpw** [comment]
My tests indicate these do not allow bypassing of the class filter, and therefore this is not a sandbox leak.

**Comment by Exidex** [comment]
You are right
this
```
print(com.example.examplemod.ExampleMod);
```
prints this
```
[JavaPackage com.example.examplemod.ExampleMod]
```
but when you actually call the method it throws ClassNotFoundException,
Sorry for the confusion

**Comment by cpw** [comment]
Thanks for checking.
